// Auto-generated by scripts/sync-frontend.js
// Do not edit manually
// Last updated: 2025-12-08T12:02:30.000Z

import LendingPoolABI from '../abis/LendingPool.json';
import AutonomyVaultABI from '../abis/AutonomyVault.json';
import IPManagerABI from '../abis/IPManager.json';
import AutoRepayEngineABI from '../abis/AutoRepayEngine.json';
import InterestRateModelABI from '../abis/InterestRateModel.json';
import PriceOracleABI from '../abis/PriceOracle.json';
import USDCABI from '../abis/USDC.json';
import USDTABI from '../abis/USDT.json';
import WETHABI from '../abis/WETH.json';
import WBTCABI from '../abis/WBTC.json';
import DAIABI from '../abis/DAI.json';
import LINKABI from '../abis/LINK.json';
import UNIABI from '../abis/UNI.json';
import AAVEABI from '../abis/AAVE.json';
import MockRoyaltyTokenABI from '../abis/MockRoyaltyToken.json';
import MockIPAssetRegistryABI from '../abis/MockIPAssetRegistry.json';
import MockRoyaltyVaultABI from '../abis/MockRoyaltyVault.json';
import MockRoyaltyModuleABI from '../abis/MockRoyaltyModule.json';
import MockUniswapRouterABI from '../abis/MockUniswapRouter.json';
import StoryRoyaltySimulatorABI from '../abis/StoryRoyaltySimulator.json';
import RoyaltyTokenABI from '../abis/RoyaltyToken.json';
import AutoRepayVaultABI from '../abis/AutoRepayVault.json';
import MockLendingPoolABI from '../abis/MockLendingPool.json';

// Network-specific contract addresses
export const CONTRACTS = {
    1315: { // storyAeneid
        LENDING_POOL: {
            address: "0x3358f984e9b3cbbe976eefe9b6fb92a214162932" as const,
            abi: LendingPoolABI,
        },
        AUTONOMY_VAULT: {
            address: "0x95d7ff1684a8f2e202097f28dc2e56f773a55d02" as const,
            abi: AutonomyVaultABI,
        },
        IP_MANAGER: {
            address: "0x897945a56464616a525c9e5f11a8d400a72a8f3a" as const,
            abi: IPManagerABI,
        },
        AUTO_REPAY_ENGINE: {
            address: "0x633a7eb9b8912b22f3616013f3153de687f96074" as const,
            abi: AutoRepayEngineABI,
        },
        INTEREST_RATE_MODEL: {
            address: "0xd8fe7c45330c8b12ca0d4728d75557b9e7beb24f" as const,
            abi: InterestRateModelABI,
        },
        PRICE_ORACLE: {
            address: "0x69eb226983e10d7318816134cd44be3023dc74cd" as const,
            abi: PriceOracleABI,
        },
        USDC: {
            address: "0x43c5df0c482c88cef8005389f64c362ee720a5bc" as const,
            abi: USDCABI,
        },
        USDT: {
            address: "0x2098cb47b17082ab6969fb2661f2759a9bf357c4" as const,
            abi: USDTABI,
        },
        WETH: {
            address: "0xf01f4567586c3a707ebec87651320b2dd9f4a287" as const,
            abi: WETHABI,
        },
        WBTC: {
            address: "0x2b07f89c9f574a890f5b8b7fddafbbae40f6fde2" as const,
            abi: WBTCABI,
        },
        DAI: {
            address: "0xcac60200c1cb424f2c1e438c7ee1b98d487f0254" as const,
            abi: DAIABI,
        },
        LINK: {
            address: "0xabc84968376556b5e5b3c3bda750d091a06de536" as const,
            abi: LINKABI,
        },
        UNI: {
            address: "0xff8fa9381caf61cb3368a6ec0b3f5c788028d0cd" as const,
            abi: UNIABI,
        },
        AAVE: {
            address: "0xe55cc27460b55c8ac7e73043f38b537758c9e51e" as const,
            abi: AAVEABI,
        },
        MockRoyaltyToken: {
            address: "0x5aa185fbefc205072faecc6b9d564383e761f8c2" as const,
            abi: MockRoyaltyTokenABI,
        },
        MockIPAssetRegistry: {
            address: "0xa4f9885550548c6a45b9d18c57b114c06f3c39b8" as const,
            abi: MockIPAssetRegistryABI,
        },
        MockRoyaltyVault: {
            address: "0x886a2a3abf5b79aa5dff1c73016bd07cfc817e04" as const,
            abi: MockRoyaltyVaultABI,
        },
        MockRoyaltyModule: {
            address: "0x449c286ab90639fd9f6604f4f15ec86bce2b8a61" as const,
            abi: MockRoyaltyModuleABI,
        },
        MockUniswapRouter: {
            address: "0x63275d081c4a77ae69f76c4952f9747a5559a519" as const,
            abi: MockUniswapRouterABI,
        },
        STORY_ROYALTY_SIMULATOR: {
            address: "0x7B670a01E1D521ff232846dE0F7fE857a85c37A6" as const,
            abi: StoryRoyaltySimulatorABI,
        },
        ROYALTY_TOKEN: {
            address: "0x242e50f40E771da8F19aAF1b813658A8562B2ad2" as const,
            abi: RoyaltyTokenABI,
        },
        AUTO_REPAY_VAULT: {
            address: "0x366FDba679A8ece0567C1aFFC8C543f6FE9964d5" as const,
            abi: AutoRepayVaultABI,
        },
        MOCK_LENDING_POOL: {
            address: "0x0a5e677a6A24b2F1A2Bf4F3bFDC6c7D096d9e8f8" as const,
            abi: MockLendingPoolABI,
        },
        MOCK_ROYALTY_TOKEN: {
            address: "0xA272fB0D17DC50652Fda5cF1651C6f8f21Fb02A8" as const,
            abi: MockRoyaltyTokenABI,
        },
    },
} as const;

// Helper to get contracts for current chain
export const getContracts = (chainId: number) => {
    return CONTRACTS[chainId as keyof typeof CONTRACTS];
};

export const SUPPORTED_CHAIN_IDS = [1315] as const;

// All market data, liquidity, and APY/APR come from Story Aeneid
export const MARKET_CHAIN_ID = 1315;

// Backward compatibility - Story Aeneid is the only chain
export const CHAIN_ID = MARKET_CHAIN_ID;
