// Auto-generated by scripts/sync-frontend.js
// Do not edit manually

import LendingPoolABI from '../abis/LendingPool.json';
import AutonomyVaultABI from '../abis/AutonomyVault.json';
import IPManagerABI from '../abis/IPManager.json';
import AutoRepayEngineABI from '../abis/AutoRepayEngine.json';
import InterestRateModelABI from '../abis/InterestRateModel.json';
import PriceOracleABI from '../abis/PriceOracle.json';
import USDCABI from '../abis/USDC.json';
import USDTABI from '../abis/USDT.json';
import WETHABI from '../abis/WETH.json';
import WBTCABI from '../abis/WBTC.json';
import DAIABI from '../abis/DAI.json';
import LINKABI from '../abis/LINK.json';
import UNIABI from '../abis/UNI.json';
import AAVEABI from '../abis/AAVE.json';
import MockRoyaltyTokenABI from '../abis/MockRoyaltyToken.json';
import MockIPAssetRegistryABI from '../abis/MockIPAssetRegistry.json';
import MockRoyaltyVaultABI from '../abis/MockRoyaltyVault.json';
import MockRoyaltyModuleABI from '../abis/MockRoyaltyModule.json';
import MockUniswapRouterABI from '../abis/MockUniswapRouter.json';

export const CONTRACTS = {
    LENDING_POOL: {
        address: "0xb7f8bc63bbcad18155201308c8f3540b07f84f5e",
        abi: LendingPoolABI,
    },
    AUTONOMY_VAULT: {
        address: "0xc6e7df5e7b4f2a278906862b61205850344d4e7d",
        abi: AutonomyVaultABI,
    },
    IP_MANAGER: {
        address: "0x59b670e9fa9d0a427751af201d676719a970857b",
        abi: IPManagerABI,
    },
    AUTO_REPAY_ENGINE: {
        address: "0x4ed7c70f96b99c776995fb64377f0d4ab3b0e1c1",
        abi: AutoRepayEngineABI,
    },
    INTEREST_RATE_MODEL: {
        address: "0x610178da211fef7d417bc0e6fed39f05609ad788",
        abi: InterestRateModelABI,
    },
    PRICE_ORACLE: {
        address: "0x2279b7a0a67db372996a5fab50d91eaa73d2ebe6",
        abi: PriceOracleABI,
    },
    USDC: {
        address: "0x5fbdb2315678afecb367f032d93f642f64180aa3",
        abi: USDCABI,
    },
    USDT: {
        address: "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512",
        abi: USDTABI,
    },
    WETH: {
        address: "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0",
        abi: WETHABI,
    },
    WBTC: {
        address: "0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9",
        abi: WBTCABI,
    },
    DAI: {
        address: "0xdc64a140aa3e981100a9beca4e685f962f0cf6c9",
        abi: DAIABI,
    },
    LINK: {
        address: "0x5fc8d32690cc91d4c39d9d3abcbd16989f875707",
        abi: LINKABI,
    },
    UNI: {
        address: "0x0165878a594ca255338adfa4d48449f69242eb8f",
        abi: UNIABI,
    },
    AAVE: {
        address: "0xa513e6e4b8f2a923d98304ec87f64353c4d5c853",
        abi: AAVEABI,
    },
    MockRoyaltyToken: {
        address: "0x4826533b4897376654bb4d4ad88b7fafd0c98528",
        abi: MockRoyaltyTokenABI,
    },
    MockIPAssetRegistry: {
        address: "0x95401dc811bb5740090279ba06cfa8fcf6113778",
        abi: MockIPAssetRegistryABI,
    },
    MockRoyaltyVault: {
        address: "0x998abeb3e57409262ae5b751f60747921b33613e",
        abi: MockRoyaltyVaultABI,
    },
    MockRoyaltyModule: {
        address: "0x70e0ba845a1a0f2da3359c97e0285013525ffc49",
        abi: MockRoyaltyModuleABI,
    },
    MockUniswapRouter: {
        address: "0x99bba657f2bbc93c02d617f8ba121cb8fc104acf",
        abi: MockUniswapRouterABI,
    },
} as const;

export const CHAIN_ID = 31337;
