// Auto-generated by scripts/sync-frontend.js
// Do not edit manually
// Last updated: 2025-12-07T06:21:35.287Z

import LendingPoolABI from '../abis/LendingPool.json';
import AutonomyVaultABI from '../abis/AutonomyVault.json';
import IPManagerABI from '../abis/IPManager.json';
import AutoRepayEngineABI from '../abis/AutoRepayEngine.json';
import InterestRateModelABI from '../abis/InterestRateModel.json';
import PriceOracleABI from '../abis/PriceOracle.json';
import USDCABI from '../abis/USDC.json';
import USDTABI from '../abis/USDT.json';
import WETHABI from '../abis/WETH.json';
import WBTCABI from '../abis/WBTC.json';
import DAIABI from '../abis/DAI.json';
import LINKABI from '../abis/LINK.json';
import UNIABI from '../abis/UNI.json';
import AAVEABI from '../abis/AAVE.json';
import MockRoyaltyTokenABI from '../abis/MockRoyaltyToken.json';
import MockIPAssetRegistryABI from '../abis/MockIPAssetRegistry.json';
import MockRoyaltyVaultABI from '../abis/MockRoyaltyVault.json';
import MockRoyaltyModuleABI from '../abis/MockRoyaltyModule.json';
import MockUniswapRouterABI from '../abis/MockUniswapRouter.json';

// Network-specific contract addresses
export const CONTRACTS = {
    1315: { // storyAeneid
        LENDING_POOL: {
            address: "0xb1c05b498cb58568b2470369feb98b00702063da" as const,
            abi: LendingPoolABI,
        },
        AUTONOMY_VAULT: {
            address: "0xa195acceb1945163160cd5703ed43e4f78176a54" as const,
            abi: AutonomyVaultABI,
        },
        IP_MANAGER: {
            address: "0x6212cb549de37c25071cf506ab7e115d140d9e42" as const,
            abi: IPManagerABI,
        },
        AUTO_REPAY_ENGINE: {
            address: "0x6f9679bdf5f180a139d01c598839a5df4860431b" as const,
            abi: AutoRepayEngineABI,
        },
        INTEREST_RATE_MODEL: {
            address: "0x89372b32b8af3f1272e2efb3088616318d2834ca" as const,
            abi: InterestRateModelABI,
        },
        PRICE_ORACLE: {
            address: "0x04f339ec4d75cf2833069e6e61b60ef56461cd7c" as const,
            abi: PriceOracleABI,
        },
        USDC: {
            address: "0x7036124464a2d2447516309169322c8498ac51e3" as const,
            abi: USDCABI,
        },
        USDT: {
            address: "0xee1eb820beeced56657ba74fa8d70748d7a6756c" as const,
            abi: USDTABI,
        },
        WETH: {
            address: "0x5c932424acbfab036969b3b9d94ba9ecbae7565d" as const,
            abi: WETHABI,
        },
        WBTC: {
            address: "0x3949c97925e5aa13e34ddb18eabf0b70abb0c7d4" as const,
            abi: WBTCABI,
        },
        DAI: {
            address: "0x9e7f7d0e8b8f38e3cf2b3f7dd362ba2e9e82baa4" as const,
            abi: DAIABI,
        },
        LINK: {
            address: "0x0724f18b2aa7d6413d3fdcf6c0c27458a8170dd9" as const,
            abi: LINKABI,
        },
        UNI: {
            address: "0xe7ff84df24a9a252b6e8a5bb093ac52b1d8beedf" as const,
            abi: UNIABI,
        },
        AAVE: {
            address: "0x6d712cb50297b97b79de784d10f487c00d7f8c2c" as const,
            abi: AAVEABI,
        },
        MockRoyaltyToken: {
            address: "0x2498e8059929e18e2a2ced4e32ef145fa2f4a744" as const,
            abi: MockRoyaltyTokenABI,
        },
        MockIPAssetRegistry: {
            address: "0x3abbb0d6ad848d64c8956edc9bf6f18ac22e1485" as const,
            abi: MockIPAssetRegistryABI,
        },
        MockRoyaltyVault: {
            address: "0x021dbff4a864aa25c51f0ad2cd73266fde66199d" as const,
            abi: MockRoyaltyVaultABI,
        },
        MockRoyaltyModule: {
            address: "0x4cf4dd3f71b67a7622ac250f8b10d266dc5aebce" as const,
            abi: MockRoyaltyModuleABI,
        },
        MockUniswapRouter: {
            address: "0x447786d977ea11ad0600e193b2d07a06efb53e5f" as const,
            abi: MockUniswapRouterABI,
        },
    },
} as const;

// Helper to get contracts for current chain
export const getContracts = (chainId: number) => {
    return CONTRACTS[chainId as keyof typeof CONTRACTS];
};

export const SUPPORTED_CHAIN_IDS = [1315] as const;

// All market data, liquidity, and APY/APR come from Story Aeneid
export const MARKET_CHAIN_ID = 1315;

// Backward compatibility - Story Aeneid is the only chain
export const CHAIN_ID = MARKET_CHAIN_ID;
